### ISSUE TITLE
MONITOR= env var not being honoured

### ISSUE THREAD

**Issue by cbrherms** [pyouroboros/ouroboros#171]
Was comfortably using ouroboros from the old docker repo for a fair few months.

Noticed that repo has now changed so double checked my env vars, adjusted to new namings and deployed.

Looks like the MONITOR environment variable is now not being honoured though as logs indicate `Running *all*`
Not so much of an issue on one of my environments but this has caused an unknown issue with a remote docker test site I manage. That one is currently down so will have to look in to that issue when i'm next on site, but likely it's done the same and updated all containers, causing my proxies to fail.

On the site I can currently access, ouroboros part of the docker-compose file is as follows:

```
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    environment:
      - INTERVAL=3600
      - LOGLEVEL=info
      - MONITOR=portainer
      - SELF_UPDATE=true
    image: pyouroboros/ouroboros
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
```
