### ISSUE TITLE
Slack notifications via webhook not working

### ISSUE THREAD

**Issue by liangmicha** [pyouroboros/ouroboros#187]
Hi there,

I have the following in my docker-compose.yml but I am not seeing any slack notifications come through:
```
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=30
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - MONITOR=app
      - TZ=America/Los_Angeles
      - REPO_USER=$DOCKER_USERNAME
      - REPO_PASS=$DOCKER_PASSWORD
      - WEBHOOK_URLS=$SLACK_WEBHOOK_URL
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

Everything else works fine (auto-updating), it's just that I don't think it's sending a request to the webhook.
 
`$SLACK_WEBHOOK_URL` is something like https://hooks.slack.com/services/<characters_and_numbers>/<characters_and_numbers>/<characters>

When I manually CURL that slack webhook url, it's working fine.

I'm guessing there's some error in my setup, any help or tips is appreciated :)
