### ISSUE TITLE
ouroboros exception when running 

### ISSUE THREAD

**Issue by bilago** [pyouroboros/ouroboros#226]
I've had ouroboros installed for about a week now on Ubuntu 18.10 and I've had to remove the ouroboros image and reinstall it twice now for this error. Once set up again it runs fine the first time, then after that I get this exception. Please advise:

`2019-02-17 16:40:25 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-02-17 16:45:25 EST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 276, in update
    updateable, depends_on_containers, hard_depends_on_containers = self.socket_check()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 241, in socket_check
    if current_image.id != latest_image.id:
AttributeError: 'NoneType' object has no attribute 'id'
2019-02-17 16:45:25 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-02-17 16:50:25 EST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 276, in update
    updateable, depends_on_containers, hard_depends_on_containers = self.socket_check()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 241, in socket_check
    if current_image.id != latest_image.id:
AttributeError: 'NoneType' object has no attribute 'id'
2019-02-17 16:50:25 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-02-17 16:55:25 EST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 276, in update
    updateable, depends_on_containers, hard_depends_on_containers = self.socket_check()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 241, in socket_check
    if current_image.id != latest_image.id:
AttributeError: 'NoneType' object has no attribute 'id'
2019-02-17 16:55:25 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-02-17 17:00:25 EST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 276, in update
    updateable, depends_on_containers, hard_depends_on_containers = self.socket_check()
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 241, in socket_check
    if current_image.id != latest_image.id:
AttributeError: 'NoneType' object has no attribute 'id'
2019-02-17 18:02:58 : INFO : ouroboros : Version: 1.2.1-master`

**Comment by DirtyCajunRice** [comment]
please post your config settings (first line in debug output on start)

**Comment by bilago** [comment]
Log level is currently at info, i'll change it to debug, however reinstalling the image will fix the problem for now so it might be a bit before I can replicate the error message above.

How i installed the image:


```
docker create \
--name=ouroboros \
-e CLEANUP=true \
-e INTERVAL=300 \
-e LOG_LEVEL=info \
-e SELF_UPDATE=true \
-e IGNORE=mongo \
-e IGNORE=influxdb \
-e IGNORE=postgres \
-e IGNORE=mariadb \
-e TZ=America/New_York \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /home/bilago/.docker:/root/.docker \
pyouroboros/ouroboros
```

**Comment by bilago** [comment]
config settings with debug enabled:


`2019-02-17 18:15:48 : DEBUG : ouroboros : Ouroboros configuration:
 {
'interval': 300, 
'docker_sockets': ['unix://var/run/docker.sock'], 
'ignore': ['mariadb'], 
'log_level': 'debug', 
'prometheus_addr': None, 
'prometheus_port': None, 
'cleanup': True, 
'influx_url': None,
 'influx_port': None, 
'influx_username': None, 
'influx_password': None, 
'self_update': True, 
'hostname': '5b7980c51586', 
'docker_tls_verify': True
}`

**Comment by DirtyCajunRice** [comment]
im almost certain you are on 1.2.0. this was fixed in 1.2.1

**Comment by bilago** [comment]
According to the logs:

`INFO : ouroboros : Version: 1.2.1-master`

**Comment by DirtyCajunRice** [comment]
can you completely remove the container and image(s) for ouroboros and pull a clean fresh image? the error you are getting shouldnt be possible with the current code

**Comment by bilago** [comment]
did the following

- docker stop ouroboros
- docker remove ouroboros
- docker rmi pyouroboros/ouroboros
- docker pull pyouroboros/ouroboros
- installed using my docker create command

I'll update this bug report with my results as it might take some time before the error occurs again

**Comment by DirtyCajunRice** [comment]
As a side note, multiple ignores dont work like that. An environment variable cannot be set more than once, so the last ignore is the only ignore that will work. Instead do `-e IGNORE=mongo influxdb postgres mariadb`

**Comment by tonobo** [comment]
I've experienced the same issue by accessing our private registry. 

```
2019-02-19 10:09:53 : DEBUG : dockerclient : Checking tag: registry.example.com/path/to/docker:experimental
2019-02-19 10:09:53 : DEBUG : connectionpool : http://localhost:None "GET /v1.35/distribution/registry.example.com/path/to/docker:experimental/json HTTP/1.1" 500 135
```

docker-compose.yml

```yaml
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      CLEANUP: "true"
      INTERVAL: 30
      LOG_LEVEL: debug
      SELF_UPDATE: "true"
      LABEL_ENABLE: "true"
      LABELS_ONLY: "true"
      DRY_RUN: "true"
      REPO_USER: gitlab-user
      REPO_PASS: secret
      TZ: Europe/Berlin
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.dockercfg
      - /root/.docker/config.json:/root/.docker/config.json
```

/root/.docker/config.json:
```
{
	"auths": {
		"registry.example.com": {
			"auth": "secret"
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.09.2 (linux)"
	}
}
```

**Comment by zegervdv** [comment]
I've got the same issue too:
```
ouroboros | 2019-02-20 10:07:44 : INFO : ouroboros : Version: 1.2.1-master
ouroboros | 2019-02-20 10:07:46 : ERROR : base : Job "Initial run interval container update for unix://var/run/docker.sock (trigger: date[2019-02-20 10:07:44 UTC], next run at: 2019-02-20 10:07:44 UTC)" raised an exception
ouroboros | Traceback (most recent call last): 
ouroboros |   File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
ouroboros |     retval = job.func(*job.args, **job.kwargs)
ouroboros |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 276, in update
ouroboros |     updateable, depends_on_containers, hard_depends_on_containers = self.socket_check()
ouroboros |   File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 241, in socket_check
ouroboros |     if current_image.id != latest_image.id:
ouroboros | AttributeError: 'NoneType' object has no attribute 'id' 
```

I am also using a private registry.

Configuration:
```
ouroboros:
  image: pyouroboros/ouroboros:latest
  container_name: ouroboros
  restart: unless-stopped
  environment: 
    - DATA_EXPORT=prometheus
    - PROMETHEUS_ADDR=0.0.0.0
    - PROMETHEUS_PORT=8000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock 
    - ./config.json:/root/.docker/config.json:ro
  command: --label-enable --labels-only --interval 30
```
