### ISSUE TITLE
randomly Stopped with exit code 137

### ISSUE THREAD

**Issue by si458** [pyouroboros/ouroboros#235]
for some reason the container running ouroboros keeps stopping after a few minutes of being up?

my config is a stack V2

```
version: '2'
services:
  ouroboros:
    image: pyouroboros/ouroboros:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=debug
      - NOTIFIERS=pover://abc@xyz
      - PROMETHEUS_ADDR=0.0.0.0
      - DATA_EXPORT=prometheus 
    networks:
      - default
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090
    networks:
      - default
      - grafana
networks:
  grafana:
    external:
      name: grafana_default
```

the debug logs arent really helpful either?
https://pastebin.com/raw/g95BYCRe

any suggestion
