### ISSUE TITLE
Child container with --network parameter is not supported

### ISSUE THREAD

**Issue by azinchen** [pyouroboros/ouroboros#239]
Looks like, this image has the same issue as in original, https://github.com/v2tec/watchtower/issues/188

```
version: '3'

services:
  vpn:
    image: azinchen/nordvpn:latest
    cap_add:
      - net_admin
    devices:
      - /dev/net/tun
...

  transmission:
    image: linuxserver/transmission:latest
    network_mode: service:vpn
    depends_on:
      - vpn
...
```

If 'vpn' container is updated, 'transmission' container network is not linked to 'vpn' network.

I haven't checked it yet, but I'm pretty sure, that when 'transmission' container is updated, it will not be created as in original issue.

**Comment by DirtyCajunRice** [comment]
What version are you on. We are now leaving the prior sha as an alias.

**Comment by azinchen** [comment]
I used docker-compose.yml example file, without IGNORE and TZ environment variables.

**Comment by DirtyCajunRice** [comment]
Sorry i mean what version of ouroboros are you on. In addition, v1.3.0 is being released today so i would also like you to test on that as well

**Comment by azinchen** [comment]
I use https://github.com/pyouroboros/ouroboros/blob/master/docker-compose.yml file. I'll tell you how it works today.

**Comment by azinchen** [comment]
`transmission` network before updating `vpn` container

```
root@c61564fbaed8:/$ ifconfig
eth0      Link encap:Ethernet  HWaddr 02:42:AC:12:00:03
          inet addr:172.18.0.3  Bcast:172.18.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:35226519 errors:0 dropped:0 overruns:0 frame:0
          TX packets:63604043 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:4618811233 (4.3 GiB)  TX bytes:85256484591 (79.4 GiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:341 errors:0 dropped:0 overruns:0 frame:0
          TX packets:341 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:24655 (24.0 KiB)  TX bytes:24655 (24.0 KiB)

tun0      Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:10.8.1.15  P-t-P:10.8.1.15  Mask:255.255.255.0
          UP POINTOPOINT RUNNING NOARP MULTICAST  MTU:1500  Metric:1
          RX packets:3724413 errors:0 dropped:0 overruns:0 frame:0
          TX packets:6389349 errors:0 dropped:7860 overruns:0 carrier:0
          collisions:0 txqueuelen:100
          RX bytes:218759069 (208.6 MiB)  TX bytes:8558827161 (7.9 GiB)
```

`ouroboros` log

```
2019-02-25 19:26:03 : INFO : ouroboros : Version: 1.3.0-master
2019-02-25 19:42:07 : INFO : dockerclient : transmission_vpn_1 will be updated
```

`transmission` network after updating `vpn` container

```
root@c61564fbaed8:/$ ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:341 errors:0 dropped:0 overruns:0 frame:0
          TX packets:341 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:24655 (24.0 KiB)  TX bytes:24655 (24.0 KiB)
```

**Comment by azinchen** [comment]
Now I have log that confirms the same issue as in watchtower.
`ouroboros` cannot update container which has --network parameter

```
2019-02-25 21:57:14 : INFO : dockerclient : transmission_transmission_1 will be updated
2019-02-25 21:57:26 : ERROR : base : Job "Interval container update for unix://var/run/docker.sock (trigger: interval[0:05:00], next run at: 2019-02-25 22:01:03 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 256, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localhost/v1.35/containers/create?name=transmission_transmission_1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 317, in update
    self.recreate(container, latest_image)
  File "/usr/local/lib/python3.7/site-packages/pyouroboros/dockerclient.py", line 137, in recreate
    created = self.client.api.create_container(**new_config)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 427, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.7/site-packages/docker/api/container.py", line 438, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 262, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.7/site-packages/docker/api/client.py", line 258, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("conflicting options: hostname and the network mode")
```

**Comment by DirtyCajunRice** [comment]
thats actually incorrect. only hostname and net: container are incompatible. we still dont have a sane way to non aggressively check for net:container. i might add a label for it to make it a passive query.

**Comment by azinchen** [comment]
There are two issues.
First, when base container is updating. In this case, child container loses network.
Second, when child container is updating. In this case, "conflicting options" occurs.

**Comment by ryester27** [comment]
> There are two issues.
> First, when base container is updating. In this case, child container loses network.
> Second, when child container is updating. In this case, "conflicting options" occurs.

For the first issue, you can use the **com.ouroboros.depends_on** label to make sure that the child 'transmission' container restarts after the 'vpn' update is finished. I have the same issue, and it sounds like a Docker limitation to me

For the second issue, as DirtyCajunRice said, it's due to the hostname of the 'vpn' container being inherited. When ouroboros duplicates the config during update, it's trying to create a second container with the same hostname, and Docker doesn't like that.

**Comment by azinchen** [comment]
Could you provide the particular example what should be added to original compose file?

**Comment by ryester27** [comment]
> Could you provide the particular example what should be added to original compose file?

I haven't really messed with compose files all that much, but these resources should help:

https://docs.docker.com/compose/compose-file/#labels
 https://github.com/pyouroboros/ouroboros/wiki/Usage#labels

**Comment by circa10a** [comment]
@azinchen is this still an issue after using labels?

**Comment by tyr84** [comment]
I don't understand how labels will fix the second issue? Isn't the problem that with "--net:container" the container is recreated with improper settings?

**Comment by azinchen** [comment]
I found another issue, https://github.com/pyouroboros/ouroboros/issues/246, which wasn't fixed. I decided to switch back to watchtower, because that image has less issues...

**Comment by markolonius** [comment]
docker.errors.APIError: 400 Client Error: Bad Request ("conflicting options: hostname and the network mode")

I have been getting the error daily.  Any specific logs that I could provide that might help?

**Comment by kevlar1818** [comment]
It seems to me the "needs more info" label in this ticket is stale. I think there's a fairly clear understanding of the issue(s) at hand. Could we remove the "needs more info" label in the interest of raising the visibility of this important defect?

**Comment by fad6b5f049** [comment]
+1, this feature is essential to me before I can start using ouroboros again. Until then, manually updating it is.

**Comment by nemchik** [comment]
Having the same (or very similar) issue reported from a DS user who has Jackett, DelugeVPN, and Ouroboros running. Here is the relevant sections of the compose file used (removed fluff like labels and logging which are irrelevant in this scenario):

```yaml
version: "3.4"
services:

  delugevpn:
    cap_add:
      - NET_ADMIN
    container_name: delugevpn
    environment:
      - ENABLE_PRIVOXY=${DELUGEVPN_ENABLE_PRIVOXY}
      - LAN_NETWORK=${LAN_NETWORK}
      - NAME_SERVERS=${NS1},${NS2}
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
      - VPN_ENABLED=${VPN_ENABLE}
      - VPN_OPTIONS=${VPN_OPTIONS}
      - VPN_PASS=${VPN_PASS}
      - VPN_PROV=${VPN_PROV}
      - VPN_USER=${VPN_USER}
    hostname: ${DOCKERHOSTNAME}
    image: binhex/arch-delugevpn
    ports:
      - ${DELUGEVPN_PORT_58846}:58846
      - ${DELUGEVPN_PORT_58946}:58946
      - ${DELUGEVPN_PORT_8112}:8112
      - ${DELUGEVPN_PORT_8118}:8118
      - ${JACKETT_PORT_9117}:9117
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/delugevpn:/config
      - ${DOCKERSHAREDDIR}:/shared
      - ${DOWNLOADSDIR}:/data
      - ${DOWNLOADSDIR}:/downloads

  jackett:
    container_name: jackett
    depends_on:
      - delugevpn
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    image: linuxserver/jackett
    network_mode: "container:delugevpn"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DOCKERCONFDIR}/jackett:/config
      - ${DOCKERSHAREDDIR}:/shared
      - ${DOWNLOADSDIR}:/data
      - ${DOWNLOADSDIR}:/downloads

  ouroboros:
    container_name: ouroboros
    environment:
      - CLEANUP=${OUROBOROS_CLEANUP}
      - CRON=${OUROBOROS_CRON}
      - IGNORE=${OUROBOROS_IGNORE}
      - INTERVAL=${OUROBOROS_INTERVAL}
      - LOG_LEVEL=${OUROBOROS_LOG_LEVEL}
      - MONITOR=${OUROBOROS_MONITOR}
      - NOTIFIERS=${OUROBOROS_NOTIFIERS}
      - REPO_PASS=${OUROBOROS_REPO_PASS}
      - REPO_USER=${OUROBOROS_REPO_USER}
      - SELF_UPDATE=${OUROBOROS_SELF_UPDATE}
      - TZ=${TZ}
    hostname: ${DOCKERHOSTNAME}
    image: pyouroboros/ouroboros
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKERSHAREDDIR}:/shared

```

Variables used are roughly as follows (posting the default values, the user has not changed any of the defaults for Ouroboros, just the VPN specifics):

```bash
# Universal Settings
COMPOSE_HTTP_TIMEOUT=60
DOCKERCONFDIR=~/.config/appdata
DOCKERGID=999
DOCKERHOSTNAME=DockSTARTer
DOCKERLOGGING_MAXFILE=10
DOCKERLOGGING_MAXSIZE=200k
DOCKERSHAREDDIR=~/.config/appdata/shared
DOWNLOADSDIR=/mnt/downloads
MEDIADIR_AUDIOBOOKS=/mnt/medialibrary/audiobooks
MEDIADIR_BOOKS=/mnt/medialibrary/books
MEDIADIR_COMICS=/mnt/medialibrary/comics
MEDIADIR_MOVIES=/mnt/medialibrary/movies
MEDIADIR_MUSIC=/mnt/medialibrary/music
MEDIADIR_TV=/mnt/medialibrary/tv
PGID=1000
PUID=1000
TZ=America/Chicago

# VPN Settings
LAN_NETWORK=192.168.x.x/24
NS1=1.1.1.1
NS2=8.8.8.8
VPN_ENABLE=yes
VPN_OPTIONS=
VPN_PASS=
VPN_PROV=pia
VPN_USER=

### DELUGEVPN
DELUGEVPN_ENABLED=true
DELUGEVPN_BACKUP_CONFIG=true
DELUGEVPN_NETWORK_MODE=
DELUGEVPN_PORT_58846=58846
DELUGEVPN_PORT_58946=58946
DELUGEVPN_PORT_8112=8112
DELUGEVPN_PORT_8118=8118
DELUGEVPN_ENABLE_PRIVOXY=no

### JACKETT
JACKETT_ENABLED=true
JACKETT_BACKUP_CONFIG=true
JACKETT_NETWORK_MODE=
JACKETT_PORT_9117=9117

### OUROBOROS
OUROBOROS_ENABLED=true
OUROBOROS_BACKUP_CONFIG=false
OUROBOROS_NETWORK_MODE=
OUROBOROS_CLEANUP=true
OUROBOROS_CRON=0 4 * * *
OUROBOROS_IGNORE=
OUROBOROS_INTERVAL=300
OUROBOROS_LOG_LEVEL=info
OUROBOROS_MONITOR=
OUROBOROS_NOTIFIERS=
OUROBOROS_REPO_PASS=
OUROBOROS_REPO_USER=
OUROBOROS_SELF_UPDATE=true
```
