### ISSUE TITLE
docker-compose local and remote tls logger location

### ISSUE THREAD

**Issue by badsmoke** [pyouroboros/ouroboros#273]
Hello,

how can i operate a local socket and several tcp dockers with it?
Can someone please tell me a configuration for docker-compose?

My scenario:
local docker that also runs ouroboros
10 remote docker with tls client verification

thank you

**Comment by DirtyCajunRice** [comment]
please read the wiki, the above is explained in with verification and with how to address remote hosts

**Comment by badsmoke** [comment]
hello thanks for the quick answer.

I've already read the wiki, but I still haven't figured out what the folder structure for the certificate should be like.


```
version: '3'
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=debug
      - SELF_UPDATE=false
      - IGNORE=influxdb prometheus
      - TZ=Europe/Berlin
      - DATA_EXPORT=prometheus
      - PROMETHEUS_ADDR=0.0.0.0
      - PROMETHEUS_PORT=3579
      - LATEST=true
      - DOCKER_TLS=true
      - URL="unix://var/run/docker.sock tcp://remote-docker-1:2376  tcp://remote-docker-2:2376"
      - DOCKER_TLS_VERIFY=true
    ports:
      - 3579:3579
    restart: unless-stopped
    volumes:
      - /etc/docker/certs.d:/srv/docker_tls/
      - /var/run/docker.sock:/var/run/docker.sock
```
the folder /srv/docker_tls/ now contains the certificates
