### ISSUE TITLE
Document swarm configuration

### ISSUE THREAD

**Issue by molexx** [pyouroboros/ouroboros#282]
The documentation doesn't mention anything about Swarm, but there are configurations relevant to it:

I think `SWARM=true` needs to be passed.
It seems that then `LABEL_ENABLE` defaults to `true`, so `MONITOR` is ignored. I haven't tried setting it to false.

**Comment by DirtyCajunRice** [comment]
if you use swarm you have to use labels. We have made that a requirement.

**Comment by CrimsonPrince** [comment]
+111111111 This would be really useful, I'm currently confused myself.

If I get anywhere I'll write something up.

**Comment by NowayIndustries** [comment]
So I figured I would write down some of my findings, after my struggles getting ouroboros setup for swarm mode today.

Before we can even start configuring ouroboros, we have to deploy it to our host. I have done this via a stack definition, obviously.

## Initial setup
The single most important environment option is `SWARM=true`, and I have added a few complementary options.

I have added [notifications](https://github.com/pyouroboros/ouroboros/wiki/Usage#notifications), [cleanup](https://github.com/pyouroboros/ouroboros/wiki/Usage#cleanup) and [data export](https://github.com/pyouroboros/ouroboros/wiki/Usage#data-export). **That last one is useful even if you don't plan to do anything with the data (more on that later)**, _however it requires self_update to be false_ (otherwise the data export configuration is lost on a self update).

### Example stack file

```yaml
version: '3'
services:
  ouroboros:
    hostname: ouroboros
    image: pyouroboros/ouroboros:latest
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - SELF_UPDATE=false
      - TZ=Europe/Amsterdam
      - NOTIFIERS=mailto://ouroboros@domain.com?to=you@domain.com&smtp=smtp.domain.com&name=Ouroboros
      - SWARM=true
      - DATA_EXPORT=prometheus
      - PROMETHEUS_ADDR=0.0.0.0
      - PROMETHEUS_PORT=8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
```

## Configuring your stacks for auto update
When ouroboros is set to swarm mode, **it will only update services that have [the label](https://github.com/pyouroboros/ouroboros/wiki/Usage#labels)**. A very important distinction to be made here is **the difference between container labels and service labels**.

Container labels are labels applied to containers themselves, which is what ouroboros looks for when you are not in swarm mode, but you are [using labels](https://github.com/pyouroboros/ouroboros/wiki/Usage#label-enable).
Service labels are labels applied to the service itself (like the ones made for your stacks). **Ouroboros will only check the service labels when in swarm mode, container labels are ignored**.

_Whilst I have only personally observed this behaviour with the `enable` label, I am assuming it is true of the other ouroboros labels aswell._

**In order to have labels apply to the service, you must place them under the `deploy` tag in your specification**. Placing the labels directly under the service definition will cause the labels to be applied to the actual container instead.

### So a service definition that will be updated by ouroboros is:
```yml
version: '3.2'
services:
  cron:
    image: nextcloud
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    deploy:
      labels:
        - com.ouroboros.enable=true

volumes:
  nextcloud:
```

## Checking your configuration
There are serveral ways to check your configuration, I will describe two of them: Using docker's filters + the prometheus data export or by watching the ouroboros' debug logs.

### Using docker's filters
This is the most straight forward and easy way to check if your labels applied correctly, altough it does require CLI access to your docker host.

1. Login to your docker host
2. Run the command `docker service ls -q --filter "label=com.ouroboros.enable=true" | wc -l`
3. Goto the prometheus port in your browser (8000 by default) and find the value for `containers_being_monitored`

**These two numbers should the same, altough the prometheus data is only updated once every `INTERVAL` (when work is being done)**

Additionaly you could just run `docker service ls --filter "label=com.ouroboros.enable=true"` to get a list of services with the ouroboros label.

### Watching the debug logs
This method only lists the actual image names ouroboros is checking for newer versions, [you must set the `loglevel` to `debug`](https://github.com/pyouroboros/ouroboros/wiki/Usage#log-level) before you can use this.
To get a list of image names ouroboros is checking simply run
` docker service logs YOUR_OUROBOROS_SERVICE_HERE 2>&1 | grep "Checking tag:"`
the output will look like a whole lot of:
```
2019-05-26 19:17:02 : DEBUG : dockerclient : Checking tag: postgres:10
2019-05-26 19:17:06 : DEBUG : dockerclient : Checking tag: mysql:5.7.21
2019-05-26 19:17:11 : DEBUG : dockerclient : Checking tag: solidnerd/bookstack:latest
2019-05-26 19:17:12 : DEBUG : dockerclient : Checking tag: organizrtools/organizr-v2:php-fpm
2019-05-26 19:17:14 : DEBUG : dockerclient : Checking tag: couchdb:2.3.0
2019-05-26 19:17:16 : DEBUG : dockerclient : Checking tag: linuxserver/unifi:latest
2019-05-26 19:17:18 : DEBUG : dockerclient : Checking tag: swarmpit/agent:latest
2019-05-26 19:17:20 : DEBUG : dockerclient : Checking tag: swarmpit/swarmpit:latest
2019-05-26 19:17:23 : DEBUG : dockerclient : Checking tag: nextcloud:latest
2019-05-26 19:17:28 : DEBUG : dockerclient : Checking tag: portainer/portainer:latest
```
