### ISSUE TITLE
No notifications triggered when using cron

### ISSUE THREAD

**Issue by unixfox** [pyouroboros/ouroboros#289]
I've a simple docker-compose for ouroboros where I specify a CRON instead of an interval:
```yaml
version: '3.7'
services:
    ouroboros:
        image: pyouroboros/ouroboros
        environment:
            - CLEANUP=true
            - CRON="*/5 * * * *"
            - SELF_UPDATE=true
            - TZ=Europe/Brussels
            - NOTIFIERS="discord://webhook_id/webhook_token"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        deploy:
            placement:
                constraints:
                    - node.role == manager
            restart_policy:
                condition: any
```

When running using an interval I get the notification every time ouroboros do his auto update but when using a cron I get only a notification when the container gets created and that's it.

PS: I'm using the default tag of the Docker image of ouroboros: `latest`.
