### ISSUE TITLE
Ouroboros doesn't seem to remove old container before re-creating

### ISSUE THREAD

**Issue by remimikalsen** [pyouroboros/ouroboros#301]
Considering the following extract of my docker-compose.yaml:
 ```
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    networks:
      - backend
    environment:
      - CLEANUP=true
      - CRON="0 2 * * *"
      - SELF_UPDATE=true
      - TZ=${DOCKER_TZ}
NOTIFIERS="mailtos://${GMAIL_USERNAME}:${GMAIL_PASSWORD}@gmail.com?to=${NOTIFICATION_EMAIL}"
    command: --data-export prometheus --prometheus-addr 0.0.0.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/root/.docker/config.json

  nextcloud-app:
    container_name: nextcloud-app
    image: my.private.docker.registry.com/nextcloud:latest
    networks:
      - frontend
      - backend
      - email
    restart: always
    depends_on:
      - nextcloud-db
    environment:
      - TZ=${DOCKER_TZ}
      - MYSQL_DATABASE=${NEXTCLOUD_DB_NAME}
      - MYSQL_USER=${NEXTCLOUD_DB_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_HOST=nextcloud-db
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PORT=6379
    volumes:
      - nextcloud-html:/var/www/html
      - ${MY_DOCKER_DATA_DIR}/nextcloud/data:/var/www/html/data
```

Whenever Ouroboros updates my nextcloud-app container, it seems to fail to remove the old container before starting the new one. Ouroboros do not report any errors, but the nextcloud-app fails; and the remedy is always stopping it, removing it and running it again.

Could you please advise how to further debug og correct this behaviour? From the source code it seems that Ouroboros at least some places remove containers before re-running them.
