### ISSUE TITLE
How should the logs work?  Should it tell when the update is complete?

### ISSUE THREAD

**Issue by thepenguinthatwants** [pyouroboros/ouroboros#324]
Hi!

I've being using ouroboros for a while. But not sure if there is any way to check if the updates really worked? How to tell? Sometimes it has errors but later on it's just saiying  something will be updated.
```

ouroboros    | 2019-07-11 07:20:22 : INFO : dockerclient : Gitea will be updated
ouroboros    | 2019-07-11 07:20:24 : INFO : dockerclient : GiteaPostgres will be updated
ouroboros    | 2019-07-11 08:35:17 : INFO : dockerclient : Gitea will be updated
ouroboros    | 2019-07-11 09:20:26 : INFO : dockerclient : DokuWiki will be updated
ouroboros    | 2019-07-11 17:50:17 : INFO : dockerclient : Gitea will be updated
```

**Comment by thepenguinthatwants** [comment]
Hi!

Thanks for the reply.

What do you mean by the dry run enabled? I haven't put any 
Dry Run related variables or commands.

My config is like this.

```
version: '3'
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: pyouroboros/ouroboros
    restart: unless-stopped
    environment:
      - CLEANUP=true
        #      - INTERVAL=300
      - CRON="30 3 * * *"
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=mongo influxdb postgres mariadb Calibre
      - TZ=Europe/Helsinki
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```
