### ISSUE TITLE
Can't detect tag for a private registry image

### ISSUE THREAD

**Issue by vorpalhex** [pyouroboros/ouroboros#328]
This may be related to #280 

I get this message repeatedly in my Ouroboros logs:
```
2019-08-07 20:58:31 : ERROR : dockerclient : Issue detecting iris's image tag. Skipping...
2019-08-07 21:03:31 : ERROR : dockerclient : Issue detecting iris's image tag. Skipping...
```

`iris` here is a container that gets pulled from a private registry. When I run `docker images` this is the relevant output:

```
registry.gitlab.com/outlander-collective/iris   latest              603240edc4e3        21 minutes ago      171MB
registry.gitlab.com/outlander-collective/iris   <none>              486f650bac11        23 hours ago        171MB
registry.gitlab.com/outlander-collective/iris   <none>              0bf193861316        2 weeks ago         170MB
```

I would expect it to pull the latest tag? Instead it leaves it stuck on the 486f image.

**Comment by himao** [comment]
It seems that we have to explicitly use `docker run image-name:latest` instead of `docker run image-name` .Although they are the same effect. The tag looks like a required parameter.

**Comment by vorpalhex** [comment]
I am using the latest tag. Here is the docker-compose entry:
```
iris:
    container_name: iris
    hostname: iris
    image: registry.gitlab.com/outlander-collective/iris:latest
    environment:
      - "TZ=America/Chicago"
    restart: unless-stopped
```
