### ISSUE TITLE
Unexpectedly pulling all historical images with private registry

### ISSUE THREAD

**Issue by himao** [pyouroboros/ouroboros#330]
As the title describe,the update works well,but the command `docker images` list all history images.i'm sure there is just one image before the ouroboros startup.It seems like ouroboros pulling down all images in private registry to the docker host.Ouroboros and my container were created by docker-compose,my container use the image tag `latest`.
ouroboros-compose.yaml
```yaml
version: '3'
services:
  ouroboros:
    image: pyouroboros/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=debug
      - SELF_UPDATE=true
      - TZ=Asia/Shanghai
      - LABEL_ENABLE=true
      - LABELS_ONLY=true
      - DATA_EXPORT=prometheus
      - PROMETHEUS_ADDR=0.0.0.0
      - PROMETHEUS_PORT=3579
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/root/.docker/config.json
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web_net"
      - "traefik.http.routers.ouroboros.rule=Host(`ouroboros.aaa.com`)"
      - "traefik.http.services.ouroboros.loadbalancer.server.port=3579"
    networks:
      - web_net

networks:
  web_net:
    external: true
```

mycontainer-compose.yaml
```
version: '2.4'
services:
  mobile:
    image: docker.aaa.com/mobile:latest
    networks:
      - web_net
    restart: unless-stopped
    labels:
      - "com.ouroboros.enable=true"

networks: 
  web_net:
    external: true
```
the `docker images` command output
```bash
docker.aaa.com/mobile              3e3ba946            d8fe7e54723d        12 days ago         231MB
docker.aaa.com/mobile              latest              d8fe7e54723d        12 days ago         231MB
docker.aaa.com/mobile              88fdc5bd            d99dfdab935f        13 days ago         231MB
docker.aaa.com/mobile              e1b996fc            e86638d9ed38        2 weeks ago         231MB
docker.aaa.com/mobile              a6d6edfb            414c01018f51        2 weeks ago         231MB
```
It's my first times use ouroboros,maybe something wrong with my config?
