### ISSUE TITLE
Traefik 404 after Update (sometimes)

### ISSUE THREAD

**Issue by fbrinker** [pyouroboros/ouroboros#345]
I love Ouroboros, updating containers was never easier.

But from time to time I have problems with `gitea` going up again. I'm not sure if it's a problem with Traefik, Gitea or Ouroboros.

The container of Gitea updates every x hours, so i get 4 or 5 updates a day. Most of the time it works fine, but every ~3 days there is some sort of _hickup_ when updating Gitea. It doesn't get up again and Treafik displays a 404 message.

After manually running `docker-compose gitea up -d` everything is fine again.

My compose file:
```
  gitea:
    container_name: gitea
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./gitea:/data
    ports:
      - "22:22"
    restart: unless-stopped
    networks:
      - web
      - internal
    labels:
      - traefik.enable=true
      - traefik.backend=gitea
      - traefik.port=3000
      - traefik.frontend.rule=Host:...
```
... and Gitea is a dependency of another service (Drone) in that file.

Do you have any ideas why this is happening and how to avoid it? 

I am thinking of some sort of _race condition_ between Traefik and Ouroboros updating the container, but not sure where to look at and how to avoid that... esp. because it only happens every ~10+ updates...
