### ISSUE TITLE
Local build warnings

### ISSUE THREAD

**Issue by modem7** [pyouroboros/ouroboros#369]
Hey guys, 

I've got some unusual warnings, even though the images update as expected:

```
today at 6:34 AM 2020-02-14 06:34:15 : CRITICAL : dockerclient : Couldn't find an image on docker.com for linuxserver/tautulli:latest. Local Build?
today at 6:34 AM 2020-02-14 06:34:30 : CRITICAL : dockerclient : Couldn't find an image on docker.com for linuxserver/radarr:latest. Local Build?
today at 6:34 AM 2020-02-14 06:34:40 : ERROR : dockerclient : Issue detecting Nginx's image tag. Skipping...
today at 6:34 AM 2020-02-14 06:34:55 : CRITICAL : dockerclient : Couldn't find an image on docker.com for jc21/mariadb-aria:latest. Local Build?
today at 6:35 AM 2020-02-14 06:35:10 : CRITICAL : dockerclient : Couldn't find an image on docker.com for pyouroboros/ouroboros:latest. Local Build?
today at 6:35 AM 2020-02-14 06:35:20 : ERROR : dockerclient : Issue detecting DHCPRelay's image tag. Skipping...
today at 6:35 AM 2020-02-14 06:35:35 : CRITICAL : dockerclient : Couldn't find an image on docker.com for amir20/dozzle:latest. Local Build?
today at 6:35 AM 2020-02-14 06:35:50 : CRITICAL : dockerclient : Couldn't find an image on docker.com for gists/dnscrypt-proxy:latest. Local Build?
today at 6:36 AM 2020-02-14 06:36:00 : ERROR : dockerclient : Issue detecting Portainer's image tag. Skipping...
today at 7:02 AM 2020-02-14 07:02:55 : CRITICAL : dockerclient : Couldn't find an image on docker.com for linuxserver/ddclient:latest. Local Build?
today at 7:03 AM 2020-02-14 07:03:10 : CRITICAL : dockerclient : Couldn't find an image on docker.com for willfarrell/autoheal:latest. Local Build?
today at 7:03 AM 2020-02-14 07:03:20 : ERROR : dockerclient : Issue detecting Hydra2's image tag. Skipping...
today at 7:03 AM 2020-02-14 07:03:35 : CRITICAL : dockerclient : Couldn't find an image on docker.com for linuxserver/sabnzbd:latest. Local Build?
today at 7:03 AM 2020-02-14 07:03:50 : CRITICAL : dockerclient : Couldn't find an image on docker.com for linuxserver/sonarr:preview. Local Build?
today at 7:04 AM 2020-02-14 07:04:00 : ERROR : dockerclient : Issue detecting Ombi's image tag. Skipping...
today at 7:04 AM 2020-02-14 07:04:15 : CRITICAL : dockerclient : Couldn't find an image on docker.com for linuxserver/tautulli:latest. Local Build?
today at 7:04 AM 2020-02-14 07:04:30 : CRITICAL : dockerclient : Couldn't find an image on docker.com for linuxserver/radarr:latest. Local Build?
today at 7:04 AM 2020-02-14 07:04:40 : ERROR : dockerclient : Issue detecting Nginx's image tag. Skipping...
today at 7:04 AM 2020-02-14 07:04:55 : CRITICAL : dockerclient : Couldn't find an image on docker.com for jc21/mariadb-aria:latest. Local Build?
today at 7:05 AM 2020-02-14 07:05:10 : CRITICAL : dockerclient : Couldn't find an image on docker.com for pyouroboros/ouroboros:latest. Local Build?
today at 7:05 AM 2020-02-14 07:05:20 : ERROR : dockerclient : Issue detecting DHCPRelay's image tag. Skipping...
today at 7:05 AM 2020-02-14 07:05:35 : CRITICAL : dockerclient : Couldn't find an image on docker.com for amir20/dozzle:latest. Local Build?
today at 7:05 AM 2020-02-14 07:05:50 : CRITICAL : dockerclient : Couldn't find an image on docker.com for gists/dnscrypt-proxy:latest. Local Build?
today at 7:06 AM 2020-02-14 07:06:00 : ERROR : dockerclient : Issue detecting Portainer's image tag. Skipping...
```

Not quite sure what I'm doing wrong.

 ```
#Ouroboros - Docker automated image updater and cleanup
  ouroboros:
    container_name: Ouroboros
    hostname: Ouroboros
    image: pyouroboros/ouroboros
    networks: #Prevents Docker from creating a default stack network
      pihole:
        ipv4_address: '172.33.0.110'
    command: --skip-startup-notifications
    environment:
      - CLEANUP=true
      - INTERVAL=1800
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - TZ=Europe/London
      - NOTIFIERS=tgram://id:id
    restart: always
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
```
