### ISSUE TITLE
"com.ouroboros.enable=false" not working properly

### ISSUE THREAD

**Issue by lucbas** [pyouroboros/ouroboros#370]
Hi all

I have have explicitly set that ouroborus is disabled on the postgres container, but it still updated it.
Have I set the label incorrectly?

Postgres docker-compose:
```
version: '3.7'

services:
  postgres:
    image: postgres:12.1
    labels:
      ### Ouroboros config
      - "com.ouroboros.enable=false"
    restart: always
```

Ouroboros docker-compose:
```
version: '3.7'

services:
  ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/root/.docker/config.json
    environment:
      #- INTERVAL=300 # Checks every 5 minutes - value in seconds
      #- RUN_ONCE=true # testing environment requires manual trigger
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      #- IGNORE=postgres mongo # ignores the containers (container names) # done with labels
      - CLEANUP=true # deletes the old image after a successful update 
      - TZ=Europe/Zurich
      - LABELS_ONLY # ouroborus has to be explicitly enabled or disabled on a container
```

Thanks all

**Comment by cybermcm** [comment]
You have to set `- LABELS_ONLY=true` in your ouroboros config. If you set this option you can neglect the label in your postgres config...

**Comment by cybermcm** [comment]
You have to set `- LABELS_ONLY=true` in your ouroboros config. If you set this option you can neglect the label in your postgres config...

**Comment by lucbas** [comment]
Thanks, I missed that!

I updated my config to:

```
version: '3.7'

services:
  ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #- INTERVAL=300 # Checks every 5 minutes - value in seconds
      #- RUN_ONCE=true # testing environment requires manual trigger
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - CLEANUP=true # deletes the old image after a successful update
      - TZ=Europe/Zurich
      - LABELS_ONLY=true # ouroborus has to be explicitly enabled or disabled on a container
```
and:

```
version: '3.7'

services:
  app:
    image: app:latest
    labels:
      ### Ouroboros config
      - "com.ouroboros.enable=true"
    restart: always
```

When I docker-compose up Ourobors I receive the following INFO log:

```
ouroboros    | 2020-03-02 14:57:28 : INFO : ouroboros : Version: 1.4.3-master
ouroboros    | 2020-03-02 14:57:28 : WARNING : config : labels_only enabled but not in use without label_enable
ouroboros    | 2020-03-02 14:57:28 : WARNING : NotifySlack : No user was specified; using "Ouroboros".
ouroboros    | 2020-03-02 14:57:29 : INFO : dockerclient : No containers are running or monitored on ********.sock
ouroboros    | 2020-03-02 14:57:29 : WARNING : NotifySlack : Failed to send to Slack: error=200.
```
The Slack startup message is still send, but that's another thing. Primarily, I wonder why the containers are not being udpated.
I assume it is not related to the docker network as Ouroboros binds directly into the docker socket.
