### ISSUE TITLE
Ouroboros fails to detect custom tag in private repository

### ISSUE THREAD

**Issue by lucbas** [pyouroboros/ouroboros#376]
Hi all

Ouroboros fails to detect the branch-tag that we use on our GitLab.
Things were working perfectly fine before adding: 
```
      - LABELS_ONLY=true
      - LABEL_ENABLE=true
```

Here are the Ouroboros logs:
```
2020-03-05 16:05:26 : ERROR : dockerclient : Issue detecting **redacted** image tag. Skipping...
```

Here is my Ouroboros docker-compose config:
```
services:
  ouroboros:
    image: pyouroboros/ouroboros:latest
    container_name: ouroboros
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      #- INTERVAL=300 # Checks every 5 minutes - value in seconds
      #- RUN_ONCE=true # Testing environment requires manual trigger
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - CLEANUP=true # Deletes the old image after a successful update
      - TZ=Europe/Zurich
      - LABELS_ONLY=true # Ouroborus has to be explicitly enabled or disabled on a container
      - LABEL_ENABLE=true # If a container has a com.ouroboros.enable label, only watch it if it is set to true.
      - NOTIFIERS=https://hooks.slack.com/services/****
```

A sample app:
```
services:
  app1:
    image: registry.gitlab.com/***:development
    env_file:
      - ***
    networks:
      - traefik_proxy
    labels:
      ### Ouroboros config
      - com.ouroboros.enable=true
    restart: always
```
