### ISSUE TITLE
Notifications when a watched container is Started/Stopped/Restarted

### ISSUE THREAD

**Issue by t-abraham** [pyouroboros/ouroboros#378]
Hello everyone,

I am looking for the option to get notifications when a watched container is Started/Stopped/Restarted

my settings are

**docker-compose.yml**
```
version: "3.5"
services:
  ouroboros:
    image: ${IMAGE_URL}:${IMAGE_TYPE}
    container_name: ${SERVICE_NAME}
    restart: always
    env_file:
      - .env
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/.docker/config.json:/root/.docker/config.json"
    networks:
      - administration
networks:
  administration:
    name: administration
    driver: bridge
```

**.env**
```
### -------------------------------------- ###
### Docker COntainer Enviornment Variables ###
### -------------------------------------- ###

### -----------Image VARIABLES------------ ###
#IMAGE_URL=REPLACE_IMAGE_URL
#IMAGE_TYPE=stable
IMAGE_URL=pyouroboros/ouroboros
IMAGE_TYPE=latest

### -----------SYSTEM VARIABLES----------- ###
SERVICE_NAME=ouroboros
INTERVAL=60
NOTIFIERS="slack://TokenA/TokenB/TokenC/ tgram://1tgram://bottoken/ChatID"
#LABELS_ONLY=false
CLEANUP=true
SELF_UPDATE=true
LOG_LEVEL=debug
TZ=Europe/Berlin
```
