### ISSUE TITLE
Mail notification

### ISSUE THREAD

**Issue by nicx** [pyouroboros/ouroboros#59]
Hi, is it possible to get a mail notification when a container is updated or an error occured? That would be great 👍

**Comment by DirtyCajunRice** [comment]
@nicx We are updating documentation today to cover all of the refactor. I will work on adding email tonight or tomorrow :)

**Comment by DirtyCajunRice** [comment]
Merged to develop. Closing :)

**Comment by cybermcm** [comment]
Mail notification was added with 0.6.0, but I can't get it to work (no mail sent).
I tried it with the command option and env vars.

Am I doing something wrong? Is there a startup mail like watchtower?

my docker-compose file:
```
ouroboros:
  command:  --smtp-starttls --smtp-host 'mail.abc.net' --smtp-port 587 --smtp-recipients 'admin@abc.net' --smtp-from-email 'ouroboros@abc.net'
  container_name: ouroboros
  environment:
   - INTERVAL=43200
   - CLEANUP=true
   - KEEPTAG=true
   - IGNORE=apache
   #- RUNONCE=true
   - SMTP_HOST=mail.abc.net
   - SMTP_PORT=587
   - SMTP_RECIPIENTS=admin@abc.net
   - SMTP_FROM_EMAIL=ouroboros@abc.net
  image: pyouroboros/ouroboros
  restart: always
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /etc/localtime:/etc/localtime:ro
   - /var/run/docker.sock:/var/run/docker.sock
```
